name: Terraform Deploy with Monitoring

on:
  push:
    branches:
      - main  

jobs:
  terraform:
    name: Terraform Apply and Monitoring Setup
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.1

      # Add a step to navigate to the Terraform directory if necessary
      - name: Navigate to Terraform directory
        run: cd terraform  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan

      - name: Post-deployment
        run: |
          echo "Deploy complete. You can trigger notifications or further monitoring configuration here."
          # e.g., call a script: ./configure-monitoring.sh
